### ISSUE TITLE
why the packages are being built to generate documentation?

### ISSUE THREAD

**Issue by ahcorde** [ros2/docs.ros2.org#24]
Checking the [Makefile](https://github.com/ros2/docs.ros2.org/blob/doc_gen/Makefile#L141) branch `doc_gen` I noticed that some packages are being built. 

@nuclearsandwich  or @wjwwood why is this needed? Just Building the Doxyfile or/and Sphinx should be enough, right?

**Comment by dirk-thomas** [comment]
The package needs to be built on order to document generated code.

One example would be the logging macros.
