### ISSUE TITLE
Documentation about  the constant `qos_profile_sensor_data` missing in `rclpy`

### ISSUE THREAD

**Issue by goekce** [ros2/docs.ros2.org#49]
https://index.ros.org/doc/ros2/Releases/Release-Dashing-Diademata/#rclpy recommends using `qos_profile_sensor_data` for subscribers. I could not find `qos_profile_sensor_data` on the [rclpy QoS doc page](http://docs.ros2.org/foxy/api/rclpy/api/qos.html#rclpy.qos.QoSProfile).

There are some constants along with `qos_profile_sensor_data` defined on https://github.com/ros2/rclpy/blob/22816b41f66bcdb20adcca0b92fb7c8149710297/rclpy/rclpy/qos.py#L421

It would be great that these convenient constants are included in the documentation. The developer's ignorance of `qos_profile_sensor_data` leads to code as follows:

```
self.subscription = self.create_subscription(
            LaserScan,
            'scan',
            self.listener_callback,
            QoSProfile(depth=10, reliability=ReliabilityPolicy.BEST_EFFORT))
```
As far as I understand the following does the same:
```
self.subscription = self.create_subscription(
            LaserScan,
            'scan',
            self.listener_callback,
            qos_profile_sensor_data)
```

**Comment by goekce** [comment]
It makes sense that `qos_profile_sensor_data` is not documented. The typing friendly alternatives are here:

https://github.com/ros2/rclpy/blob/22816b41f66bcdb20adcca0b92fb7c8149710297/rclpy/rclpy/qos.py#L436

**Comment by goekce** [comment]
I have to amend myself. The enums defined in 

https://github.com/ros2/rclpy/blob/22816b41f66bcdb20adcca0b92fb7c8149710297/rclpy/rclpy/qos.py#L436

are as far as I understand used like this:

```py
from rclpy.qos import QoSPresetProfiles
...
self.subscription = self.create_subscription(
            LaserScan,
            'scan',
            self.listener_callback,
            QoSPresetProfiles.SENSOR_DATA.value)
```
I find the alternative `qos_profile_sensor_data` much better. Why is `qos_profile_sensor_data`  not documented? What is the recommended way of using these profiles?

**Comment by jacobperron** [comment]
I'm not sure exactly why `qos_profile_sensor_data` and other profiles are not appearing in the documentation, but it must have to do with how docs are generated for `rclpy`. It must be ignoring [this part of the `qos` module](https://github.com/ros2/rclpy/blob/22816b41f66bcdb20adcca0b92fb7c8149710297/rclpy/rclpy/qos.py#L417-L430). If you have time to look into a fix, I'm happy to review a PR in the rclpy repository. You can find build instructions for `rclpy` documentation here: https://github.com/ros2/rclpy#building-documentation

**Comment by goekce** [comment]
It was a nice introduction to Sphinx, thank you @jacobperron! See PR: https://github.com/ros2/rclpy/pull/653

**Comment by goekce** [comment]
Closing due to merge https://github.com/ros2/rclpy/pull/653
