### ISSUE TITLE
Dead link in most (all?) quality declarations

### ISSUE THREAD

**Issue by shonigmann** [ros2/docs.ros2.org#52]
Apologies in advance if this is the wrong place to post this fairly minor point, but I noticed that many (if not all) of the Quality Declaration files for core ROS packages have a dead link to a [ROS2 Onboarding Guide](https://docs.ros.org/en/foxy/Contributing/ROS-2-On-boarding-Guide.html). 

Full excerpt from _Coverage [4.iii]_:
Current coverage statistics can be viewed here. A description of how coverage statistics are calculated is summarized in this page "[ROS 2 Onboarding Guide](https://docs.ros.org/en/foxy/Contributing/ROS-2-On-boarding-Guide.html)". 

A few examples:
[rcl](https://github.com/ros2/rcl/blob/master/rcl/QUALITY_DECLARATION.md)
[rclcpp](https://github.com/ros2/rclcpp/blob/master/rclcpp/QUALITY_DECLARATION.md)
[rmw](https://github.com/ros2/rmw/blob/master/rmw/QUALITY_DECLARATION.md)

Has this guide moved somewhere else or should the reference to it be removed altogether? Is there a better document that we should direct new users (like myself) to, to learn how coverage statistics are calculated?

Thanks!

**Comment by clalancette** [comment]
Good catch.  We took the relevant parts of that guide and moved it elsewhere.  Just looking at the [rcl one](https://github.com/ros2/rcl/blob/master/rcl/QUALITY_DECLARATION.md):

* The link to the "package quality categories" looks to be just wrong, and should have pointed to REP-2004 all along
* "Semver" now exists at https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#versioning
* "Change control process" now exists at https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#change-control-process
* "Concepts" now exists at https://docs.ros.org/en/rolling/Concepts.html
* "Client libraries" now exists at https://docs.ros.org/en/rolling/Concepts/About-ROS-2-Client-Libraries.html
* "Code coverage" now exists at https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#note-on-coverage-runs
* "Performance" now exists at https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#performance
* "Linters" now exists at https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#linters-and-static-analysis

So we do indeed need an update to all of those quality declarations.

**Comment by shonigmann** [comment]
I can write a quick script to look for duplicates of those lines, update the links, and submit pull requests in the 40-odd packages with quality declarations if that would be helpful.

Just confirming that the quality declarations in the master branches should be targeting the Rolling documentation?

**Comment by clalancette** [comment]
Yeah, for the master branches, it definitely should be the Rolling documentation.  Thanks for taking this on!

**Comment by shonigmann** [comment]
Assuming I can automate this a bit, would it be worth updating the branches for other releases as well? E.g. for the foxy branch, update the links if they exist to the foxy equivalent documentation url?

**Comment by clalancette** [comment]
> Assuming I can automate this a bit, would it be worth updating the branches for other releases as well? E.g. for the foxy branch, update the links if they exist to the foxy equivalent documentation url?

Yep, that would be nice.  You'll only have to worry about the master branches and the foxy branches; we didn't have Quality Declarations before Foxy.

**Comment by shonigmann** [comment]
That should hopefully do it. I manually verified the first few (and caught one bit of sloppy code on my end that included a few extra files...), but hopefully the open PRs should be correct and as intended. Closing for now, unless someone tells me I did a horrible job.

**Comment by clalancette** [comment]
@shonigmann Thank you so much for doing this!  It really helps a lot.

**Comment by shonigmann** [comment]
Happy to help!
